//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "key_raffle")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub description: Option<String>,
    pub image_link: Option<String>,
    pub owner_id: i64,
    pub guild_id: Option<i64>,
    pub channel_id: Option<i64>,
    pub start_at: Option<DateTimeUtc>,
    pub end_at: Option<DateTimeUtc>,
    pub duration_in_seconds: Option<i32>,
    pub possible_winners: Option<i32>,
    pub create_date: DateTimeUtc,
    pub create_user_id: i64,
    pub modify_date: Option<DateTimeUtc>,
    pub modify_user_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::key_raffle_key::Entity")]
    KeyRaffleKey,
    #[sea_orm(has_many = "super::key_raffle_winner::Entity")]
    KeyRaffleWinner,
}

impl Related<super::key_raffle_key::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KeyRaffleKey.def()
    }
}

impl Related<super::key_raffle_winner::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KeyRaffleWinner.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
